version: '3.9'
services:
  backend:
    container_name: onecv-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: onecv-db
      PORT: 8080
      GIN_MODE: release

  db:
    container_name: onecv-db
    image: mysql
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-root}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DATABASE_USERNAME:-root}
      MYSQL_DATABASE: ${DATABASE_NAME:-onecv}
    ports:
      - ${DATABASE_PORT:-3306}:3306

volumes:
  mysql:
